apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellojs-deployment
  labels:
    app: hellojs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellojs
  template:
    metadata:
      labels:
        app: hellojs
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8300"
        prometheus.io/path: "/metrics"
        prometheus.io/scheme: "http"
        prometheus.io/scrape-interval: "30s"
        prometheus.io/scrape-timeout: "10s"
    spec:
      containers:
      - name: hellojs
        image: mmadhukalya/hellojs:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - name: metrics
          containerPort: 8300
        livenessProbe:
          httpGet:
            path: /ping
            port: 8300
          initialDelaySeconds: 3
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 5