apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hellojs-argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: "Timeout=180"
    argocd-image-updater.argoproj.io/image-list: hellojs=mmadhukalya/hellojs
    argocd-image-updater.argoproj.io/hellojs.update-strategy: latest
spec:
  project: default
  source:
    repoURL: https://github.com/MichaelMadhukalya/grafxp
    targetRevision: HEAD
    path: kustomize
    kustomize: {}
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
